id: paleocar_v2
title: 'PaleoCAR: SW USA Paleoclimate Reconstruction (V2)'
ordering: 2
originator: 'Bocinsky, R.K.; Kohler, T.A.'
references: >-
  Bocinsky, R. Kyle, and Timothy A. Kohler. 2014. A 2,000-year reconstruction
  of the rain-fed maize agricultural niche in the US Southwest. Nature
  Communications 5:5618. [doi:10.1038/ncomms6618](https://doi.org/10.1038/ncomms6618).


  Bocinsky, R. Kyle, Johnathan Rush, Keith W. Kintigh, and Timothy A. Kohler. 2016.  Exploration and exploitation in the macrohistory of the pre-Hispanic Pueblo Southwest.  Science Advances 2(4):e1501532. [https://doi.org/10.1126/sciadv.1501532](https://doi.org/10.1126/sciadv.1501532)
contactInformation: >-
  > DOC/NOAA/NESDIS/NCEI

  > National Centers for Environmental Information, NESDIS, NOAA, U.S.
  Department of Commerce

  > 325 Broadway, E/NE31

  > Boulder, CO 80305-3328

  > USA

  > https://www.ncdc.noaa.gov/data-access/paleoclimatology-data

  > email: paleo@noaa.gov

  > phone: 303-497-6280

  > fax: 303-497-6513
uncertainty: >-
  There are two primary sources of uncertainty in PaleoCAR reconstructions.
  The first is that the PaleoCAR algorithm attempts to select the most relevant
  three ring chronologies for reconstructing a particular variable of interest
  at a particular time. This selection process — here minimizing the predicted  residual error sum of squares (PRESS) statistic in a stepwise fashion — can  lead to different sets chronologies being selected for adjacent pixels in a  gridded reconstruction. Discrepancies between selected chronologies can  manifest as spatiotemporal "artifacts", or discontinuities (Bocinsky and  Kohler 2014:8). These are amplified by the chained mean-variance matching  technique (Bocinsky et al. 2016:10). Additional uncertainty is associated with
  the lack of fit in the regression models; fit decreases as fewer tree
  ring chronologies are available.

methodSummary: >-
  For each pixel, for each year, the model selects the tree ring chronologies
  (within a 10-degree buffer of the Four Corners states; from the National
  Tree Ring Database) that best predict PRISM data for that location and uses
  linear regression to estimate the paleoenvironmental variable for that date
  and location.


  Because the Maize Farming Niche is based on direct precipitation, maize
  farming may be possible if other water sources are utilized (e.g., springs or
  rivers) or if precipitation is concentrated on fields through water
  diversion structures (e.g., *ak chin* fields) or geologically (e.g., sand dune
  fields).
description: >-
  High spatial resolution (30 arc-second, ~800 m) Southwestern United States
  tree-ring reconstructions of May-Sept growing degree days (GDD), net
  water-year precipitation (previous Oct–Sept), and the direct precipitation
  maize farming niche (>= 1800 growing Season F GDD & >= 300 mm water-year
  precipitation).
sourceUrl: 'https://www.ncdc.noaa.gov/paleo/study/19783'
type: dataset
status: Published
revised: '2016-04-01'
region:
  zoom: 4
  center:
    - 37
    - -108.5
  resolution: 800m
  name: Southwestern USA
  style:
    color: red
    weight: 1
  extents:
    -   - 43
        - -115
    -   - 31
        - -102
timespan:
  resolution: year
  resolutionLabel: yearly
  period:
    timeZero: 1
    gte: '0001'
    lte: '2000'
    suffix: CE
variables:
  - id: ppt_water_year
    class: Precipitation
    name: Water-year (Oct-Sept) Precipitation
    units: mm
    timeseriesServiceUri: paleocar_v2/ppt_water_year
    wmsLayer: 'SKOPE:paleocar_v2_ppt_water_year_${year}'
    visible: false
    styles: 'default,raster'
    description: (prev. Oct through listed year Sept)
  - id: gdd_may_sept
    class: Temperature
    name: Summer (May-Sept) Growing Degree Days
    units: °F GDD
    timeseriesServiceUri: paleocar_v2/gdd_may_sept
    wmsLayer: 'SKOPE:paleocar_v2_gdd_may_sept_${year}'
    visible: false
    styles: 'default,raster'
    description: '°F deg.; Growing Season: May–Sept.; Divide °F GDD by 1.8 to get °C GDD'
  - id: maize_farming_niche
    class: Crop Niche
    name: Maize Farming Niche (Proportion w/i Niche - Direct Precip)
    units:
    timeseriesServiceUri: paleocar_v2/maize_farming_niche
    wmsLayer: 'SKOPE:paleocar_v2_maize_farming_niche_${year}'
    visible: false
    styles: default
    description: >-
      In niche if Growing Season F GDD (as above) >= 1800 & Water Year Precip.
      (as above) >= 300 mm; otherwise out of niche.
