FROM ghcr.io/osgeo/gdal:ubuntu-small-3.12.0

COPY --from=ghcr.io/astral-sh/uv:0.8.8 /uv /uvx /bin/

ENV UV_SYSTEM_PYTHON=1 \
    UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy

WORKDIR /ingest

COPY timeseries/ingest/pyproject.toml timeseries/ingest/uv.lock ./
COPY timeseries/ingest/src ./src
COPY timeseries/ingest/README.md ./
COPY timeseries/ingest/metadata.yml ./metadata.yml

RUN uv export --format requirements.txt --no-dev --no-emit-project --locked --no-hashes --output-file requirements.lock && \
    uv pip install --system --break-system-packages --no-cache -r requirements.lock && \
    uv pip install --system --break-system-packages --no-cache --no-deps .

CMD ["cog-stac-pipeline"]
