FROM ghcr.io/developmentseed/titiler:latest

COPY titiler_custom/ /titiler_custom/
COPY deploy/colormaps/custom.json /titiler_custom/custom.json

RUN python3 /titiler_custom/build_colormaps.py

WORKDIR /titiler_custom

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
