"""Builds the API registry (``metadata.yml``) from its split sources.

- ``<metadata-dir>/datasets/<dataset_id>.yml``: the description of a dataset and all
  of its variables, whether or not any environment publishes them.
- ``<metadata-dir>/<environment>.yml``: the data release the environment serves
  (``release:``, read by the Makefile) and, listed explicitly, the datasets and
  variables it publishes.
- ``<facts-dir>/<dataset_id>.json``: the ``dataset-facts.json`` the ingest pipeline wrote
  into that release, with the facts observed in the processed data (``crs``,
  ``transform``, ``timespan``, per-variable ``min``/``max``). The Makefile copies
  them there before the image build.

Every published variable must be described and have processed data. Observed fields
may not appear in dataset files, and the described timespan must match the processed
one. All problems are reported in one run. With ``--allow-missing-facts``
(development), datasets and variables without processed data are skipped with a
warning instead.

Runs at image build time, before any settings exist, so it must not import
``app.config``.
"""

import argparse
import json
import sys
from pathlib import Path

import yaml

OBSERVED_DATASET_KEYS = ("crs", "transform")
OBSERVED_VARIABLE_KEYS = ("min", "max")
GENERATED_HEADER = "# Generated by app.registry_build. Do not edit.\n"


class RegistryBuildError(ValueError):
    """Carries every problem found, so one build run reports them all."""


def normalize_resolution(resolution) -> dict:
    """Treats 'year', {'year': 1} and {'years': 1} as the same step.

    An empty value means the dataset has a single timestep.
    """
    if not resolution:
        return {}
    if isinstance(resolution, str):
        resolution = {resolution: 1}
    return {k if k.endswith("s") else f"{k}s": v for k, v in resolution.items()}


def _sources(dataset_id: str) -> str:
    return f"datasets/{dataset_id}.yml, {dataset_id}/dataset-facts.json in the release"


def _timespan_mismatches(described: dict, observed: dict) -> list[str]:
    errors = []
    described_period = described.get("period") or {}
    observed_period = observed.get("period") or {}
    for key in ("gte", "lte"):
        described_value = described_period.get(key)
        observed_value = observed_period.get(key)
        if str(described_value) != str(observed_value):
            errors.append(
                f"timespan.period.{key} is {described_value!r} in the dataset file "
                f"but {observed_value!r} in the processed data"
            )
    described_resolution = described.get("resolution")
    observed_resolution = observed.get("resolution")
    if normalize_resolution(described_resolution) != normalize_resolution(
        observed_resolution
    ):
        errors.append(
            f"timespan.resolution is {described_resolution!r} in the dataset file "
            f"but {observed_resolution!r} in the processed data"
        )
    return errors


def merge_dataset(
    curated: dict,
    facts: dict,
    variable_ids: list[str],
    allow_missing_facts: bool = False,
) -> tuple[dict | None, list[str]]:
    """Returns the registry entry for the selected variables, and any warnings.

    Variables keep the selection order. The entry is None when allow_missing_facts
    skipped every selected variable.
    """
    dataset_id = curated.get("id")
    errors = []
    skipped = []

    for key in OBSERVED_DATASET_KEYS:
        if key in curated:
            errors.append(
                f"'{key}' is observed in the data; remove it from the dataset file"
            )
        if key not in facts:
            errors.append(f"the release's dataset-facts.json has no '{key}'")

    described = {}
    for variable in curated.get("variables") or []:
        variable_id = variable.get("id")
        described[variable_id] = variable
        for key in OBSERVED_VARIABLE_KEYS:
            if key in variable:
                errors.append(
                    f"variable '{variable_id}': '{key}' is observed in the data; "
                    "remove it from the dataset file"
                )

    observed_variables = facts.get("variables") or {}
    variables = []
    for variable_id in variable_ids:
        variable = described.get(variable_id)
        observed = observed_variables.get(variable_id)
        if variable is None:
            errors.append(
                f"variable '{variable_id}' is selected but not described "
                "in the dataset file"
            )
            continue
        if observed is None:
            message = (
                f"variable '{variable_id}' is selected but has no processed data "
                "in the release"
            )
            (skipped if allow_missing_facts else errors).append(message)
            continue
        variables.append(
            {
                **variable,
                **{k: observed[k] for k in OBSERVED_VARIABLE_KEYS if k in observed},
            }
        )

    errors.extend(
        _timespan_mismatches(curated.get("timespan") or {}, facts.get("timespan") or {})
    )

    if errors:
        details = "\n".join(f"  - {error}" for error in errors)
        raise RegistryBuildError(f"{dataset_id} ({_sources(dataset_id)}):\n{details}")

    warnings = [f"{dataset_id}: {message}; skipped" for message in skipped]
    if not variables:
        return None, warnings

    entry = dict(curated)
    entry.update({key: facts[key] for key in OBSERVED_DATASET_KEYS})
    entry["variables"] = variables
    return entry, warnings


def _load_yaml(path: Path):
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f)


def load_dataset_sources(
    metadata_dir: Path, facts_dir: Path, dataset_id: str
) -> tuple[dict, dict | None]:
    """Returns the dataset file and the release's facts (None when it has none)."""
    curated_path = metadata_dir / "datasets" / f"{dataset_id}.yml"
    if not curated_path.is_file():
        raise RegistryBuildError(f"{dataset_id}: missing datasets/{dataset_id}.yml")

    curated = _load_yaml(curated_path)
    if not isinstance(curated, dict) or curated.get("id") != dataset_id:
        raise RegistryBuildError(
            f"{dataset_id}: datasets/{dataset_id}.yml must be a mapping "
            f"with id '{dataset_id}'"
        )

    facts_path = facts_dir / f"{dataset_id}.json"
    if not facts_path.is_file():
        return curated, None
    facts = json.loads(facts_path.read_text(encoding="utf-8"))
    if facts.get("dataset_id", dataset_id) != dataset_id:
        raise RegistryBuildError(
            f"{dataset_id}: the release's {dataset_id}/dataset-facts.json describes "
            f"'{facts.get('dataset_id')}'"
        )
    return curated, facts


def _parse_selection(selection, file_name: str) -> list[tuple[str, list[str]]]:
    """Returns (dataset_id, variable_ids) pairs from an environment file."""
    entries = selection.get("datasets") if isinstance(selection, dict) else None
    if not isinstance(entries, list):
        raise RegistryBuildError(f"{file_name} must contain a 'datasets' list")

    errors = []
    parsed = []
    seen = set()
    for index, entry in enumerate(entries):
        dataset_id = entry.get("id") if isinstance(entry, dict) else None
        variable_ids = entry.get("variables") if isinstance(entry, dict) else None
        if not isinstance(dataset_id, str) or not dataset_id:
            errors.append(f"{file_name}: dataset entry {index} has no id")
            continue
        if not isinstance(variable_ids, list) or not variable_ids:
            errors.append(
                f"{file_name}: {dataset_id} must list the variables it publishes"
            )
            continue
        if dataset_id in seen:
            errors.append(f"{file_name} lists {dataset_id} twice")
            continue
        seen.add(dataset_id)
        repeated = sorted({v for v in variable_ids if variable_ids.count(v) > 1})
        if repeated:
            errors.append(
                f"{file_name}: {dataset_id} lists {', '.join(repeated)} twice"
            )
        parsed.append((dataset_id, list(dict.fromkeys(variable_ids))))

    if errors:
        raise RegistryBuildError("\n".join(errors))
    return parsed


def build_registry(
    metadata_dir: Path,
    facts_dir: Path,
    environment: str,
    allow_missing_facts: bool = False,
) -> tuple[list[dict], list[str]]:
    """Returns the registry entries and any warnings about skipped data."""
    metadata_dir = Path(metadata_dir)
    facts_dir = Path(facts_dir)
    selection_path = metadata_dir / f"{environment}.yml"
    if not selection_path.is_file():
        raise RegistryBuildError(f"missing {selection_path.name}")

    selection = _parse_selection(_load_yaml(selection_path), selection_path.name)

    errors = []
    warnings = []
    registry = []
    for dataset_id, variable_ids in selection:
        try:
            curated, facts = load_dataset_sources(metadata_dir, facts_dir, dataset_id)
            if facts is None:
                message = (
                    f"{dataset_id}: the release has no {dataset_id}/dataset-facts.json"
                )
                if allow_missing_facts:
                    warnings.append(f"{message}; skipped")
                else:
                    errors.append(message)
                continue
            entry, entry_warnings = merge_dataset(
                curated, facts, variable_ids, allow_missing_facts
            )
            warnings.extend(entry_warnings)
            if entry is not None:
                registry.append(entry)
        except RegistryBuildError as e:
            errors.append(str(e))

    if errors:
        raise RegistryBuildError("\n".join(errors))
    return registry, warnings


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Build the API registry from dataset files, an environment file, "
        "and the release's dataset-facts.json facts."
    )
    parser.add_argument("--metadata-dir", type=Path, required=True)
    parser.add_argument("--facts-dir", type=Path, required=True)
    parser.add_argument("--environment", required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--allow-missing-facts",
        action="store_true",
        help="Skip datasets and variables without processed data (development).",
    )
    args = parser.parse_args(argv)

    try:
        registry, warnings = build_registry(
            args.metadata_dir,
            args.facts_dir,
            args.environment,
            args.allow_missing_facts,
        )
    except RegistryBuildError as e:
        print(f"Registry build failed for '{args.environment}':\n{e}", file=sys.stderr)
        return 1

    for warning in warnings:
        print(f"warning: {warning}", file=sys.stderr)
    args.output.write_text(
        GENERATED_HEADER
        + yaml.safe_dump(registry, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    print(f"Wrote {len(registry)} dataset(s) for '{args.environment}' to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
