services:
  server:
    build:
      args:
        ENVIRONMENT: dev
    image: openskope/skope-api:latest
    volumes:
      - ./timeseries/app:/code/app
      - ./timeseries/metadata.yml:/code/metadata.yml
      - ../bnd_data.nosync:/data
    ports:
    - "127.0.0.1:8001:8000"
